<?php
    $easysize_attributes = $this->getRequiredAttributes();
    $easysize_attributes_decoded = json_decode($easysize_attributes);
    if(isset($easysize_attributes_decoded) && isset($easysize_attributes_decoded->product_id)): ?>
        <script type="text/javascript" src="https://webapp.easysize.me/web_app_v1.0/js/easysize.js"></script>
        <script>
            function initEasySize() {
                var EasySize = new window.EasySize(<?php echo $easysize_attributes; ?>);
                EasySize.start();
            }

            try {
                if(EasySize) {
                    initEasySize();
                } else {
                    setTimeout(function() {
                        initEasySize();
                    }, 1000);
                }
            } catch(e) {
                console.log(e);
            }
        </script>
<?php endif; ?>